application: eventsblender
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.+\.(js|css|jpg|png|txt|html))
  static_files: static/\1
  upload: static/.+\.(js|css|jpg|png|txt|html)
  
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: markupsafe
  version: "0.15"
- name: setuptools
  version: "0.6c11"
- name: jinja2
  version: "2.6"
